import type { Metadata } from "next";
import { AppSidebar } from "@/components/layout/app-sidebar";
import { AppHeader } from "@/components/layout/app-header";
import { GlobalBreadcrumb } from "@/components/shared/global-breadcrumb";
import { ScrollArea } from "@/components/ui/scroll-area";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen overflow-hidden">
      <AppSidebar />
      <div className="flex flex-1 flex-col md:pl-[220px] lg:pl-[280px]">
        <AppHeader />
        <ScrollArea>
          <main className="flex flex-1 flex-col p-4 lg:p-6 gap-4 lg:gap-4">
            <GlobalBreadcrumb />
            {children}
          </main>
        </ScrollArea>
      </div>
    </div>
  );
}
